== Experimentos y resultados

Para comprobar la validez de los algortimos anteriores se plantearon una serie de experimentos que trabajasen sobre conjuntos de tuits escritos tanto en inglés como en español, con el objetivo de poder obtener resultados positivos a nivel de país, provincia y área metropolitana, ciudad y barrio.

La selección de los idiomas inglés y español como base para los experimentos se realizó a tenor de ser los dos lenguajes, a priori, más complejos de analizar debido a que son hablados en muchas partes del mundo. Por ejemplo, haber escogido como idioma el italiano, haría que las posibilidades de geolocalización se viesen reducidas prácticamente a Italia; ídem en el caso de haber utilizado alemán, que tan sólo es hablado en Alemania, Austria, Suiza y parte de Luxemburgo.

=== Primeros experimentos: trabajando con grandes volúmenes de datos

Los primeros experimentos se basaron en establecer diferencias a nivel de país. Para ello, se realizó un proceso de recolección de tuits durante una semana para los siguientes casos:

. Tuits de España escritos en español
. Tuits del mundo escritos en español
. Tuits del Reino Unido escritos en inglés
. Tuits del mundo escritos en inglés

En total esta fase duró 4 semanas, recolectando en torno a `2 x 8GB` de datos para los tuits globales, así como `2 x 1GB` para los tuits localizados en España y el Reino Unido.

Estos primeros conjuntos de datos permitieron que se desarrollasen los algoritmos de puntuación LLR y se empezase a comprobar empíricamente qué resultados aportaban los términos utilizados (menciones, hashtags, bigramas) así como investigar que otros campos o términos del perfil del usuario podrían ayudar a encontrar pistas acerca de su geolocalización. Durante esta fase se añadió el uso de _keywords_ tanto a nivel de contenido de un tuit como sobre el campo de localización del usuario, sospechando que podrían aportar más información útil en base a los resultados LLR que se estaban observando a nivel de bigramas.

Sobre estos conjuntos de datos no llegaron a establecerse pruebas que involucrasen software de aprendizaje automático, puesto que el uso de grandes volúmenes de datos quedó descartado al comprobar empíricamente que los términos que implican contenido geolocalizable no tienen que ser uniformes en el tiempo para una determinada región. Esta apreciación se realizó al trabajar con nuevos conjuntos de datos más pequeños, donde aparecieron como términos muy significativos aquellos que tenían que ver con un evento temporal muy concreto, el fallecimiento del seleccionador de fútbol nacional, Luis Aragonés.

.Puntuación LLR para algunos términos recogidos en conjuntos de datos entre el 1 y 2 de febrero de 2014
----
48.958529065415576  aragonés gran
49.17093149031471   aragonés selección
50.049053227619474  aragonés descanse
50.049053227619474  grandes luis
50.739417608310795  luis roja
50.97596629207029   luis nunca
50.97596629207029   luis mas
51.215854517258855  aragones hoy
51.215854517258855  aragonés historia
51.45916160893309   fútbol hombre
51.95636312422304   aragonés hombre
52.21042998468123   siempre aragones
52.46826083659376   luis mejor
52.46826083659376   dep sabio
56.28098057747021   descanse paz
81.59614077426396   fútbol grande
102.31617863438613  entrenador gran
107.56036254304512  bernabéu santiago
107.5697695101089   noticia triste
107.87375147152346  hoy madrid
111.68234684538564  hizo hombre
111.93538868096397  dep triste
115.39967536884996  fútbol va
116.50155357908382  futbol hoy
119.45187311362997  día fútbol
----

Como se puede observar, términos vinculados al fallecimiento del seleccionador aportaban una gran información geográfica que hacía que todos los tuits que los contenían prácticamente fuesen vinculados a España (lo cual en este caso sería correcto). Pero, ¿qué sucede si ocurre sobre un evento que se pueda aplicar sobre cualquier otro lugar del mundo en cualquier momento?

Por ejemplo, es habitual que durante los meses de verano en el hemisferio sur, términos relativos a la estación estival sean más habituales en países como Argentina, Chile, etc. que en España. Lo cual sería justamente al revés en épocas de verano en el hemisferio norte. Por tanto, es importante tener en cuenta que los términos y el vocabulario tienen una importancia temporal, y el hecho de obtener grandes volúmenes de datos no tiene porque beneficiar el entrenamiento de un modelo de aprendizaje automático para inferir la localización de un tuit.

Por ello, se optó por trabajar siempre con conjuntos de datos recogidos en periodos de 24 horas, para evaluarlos contra colecciones de tuits que se recogerían en las 24 horas siguientes. De esta manera se puede aprovechar la repercursión de ciertos términos ante cualquier evento.

=== Trabajando con diferentes niveles de granularidad

==== Conceptos previos

===== Acierto y exhaustividad

===== Umbral de acierto

==== Resultados a nivel de país

De acuerdo con los objetivos establecidos al comienzo del proyecto, se realizaron dos experimentos a nivel de país para poder trabajar tanto con tuits escritos en español como con aquellos escritos en inglés.

Por un lado, se realizó un experimento que pudiese discriminar tuits procedentes de España en un conjunto de tuits globales escritos en español. Por el otro, se realizó un segundo experimento enfocado en detectar qué tuits escritos en inglés desde las islas británicas procedían de la República Irlandesa.

Los resultados para ambos experimentos se pueden observar en las tablas <<experiment-spain-global>> y <<experiment-uk-ireland>>.

.Resultados de la ejecución para detectar tuits procedentes España
[cols="3,1", id="experiment-spain-global"]
|===
|Acierto
|93.16%

|Exhaustividad
|89.48%

|Acierto en predicciones locales
|96.13%

|Acierto en predicciones globales
|90.35%
|===

.Resultados de la ejecución para detectar tuits procedentes de la República Irlandesa.
[cols="3,1", id="experiment-uk-ireland"]
|===
|Acierto
|98.17%

|Exhaustividad
|71.17%

|Acierto en predicciones locales
|97.56%

|Acierto en predicciones globales
|98.20%
|===

==== Resultados a nivel de provincia

Para realizar los experimentos a nivel de provincia se seleccionaron las siguientes tres regiones del estado español: *Principado de Asturias*, *Madrid y* *Barcelona*.

En este caso, se consideró como área local cada una de las tres regiones anteriores y como área global, el total del territorio español a excepción de la provincia evaluada. Así pues, para realizar el experimento sobre el Principado de Asturias se consideró:

* *Área local*: Principado de Asturias
* *Área global*: Todo el territorio español a excepción del Principado de Asturias.

Siguiendo el mismo mecanismo en el resto de provincias.

Las tablas <<experiment-spain-asturias>>, <<experiment-spain-madrid>> y <<experiment-spain-barcelona>> muestran los resultados de la ejecución para esta granularidad.

.Resultados de la ejecución para detectar tuits procedentes del Pricipado de Asturias.
[cols="3,1", id="experiment-spain-asturias"]
|===
|Acierto
|98.89%

|Exhaustividad
|53.53%

|Acierto en predicciones locales
|89.83%

|Acierto en predicciones globales
|99.00%
|===

.Resultados de la ejecución para detectar tuits procedentes de Madrid.
[cols="3,1", id="experiment-spain-madrid"]
|===
|Acierto
|92.27%

|Exhaustividad
|72.70%

|Acierto en predicciones locales
|86.78%

|Acierto en predicciones globales
|93.39%
|===

.Resultados de la ejecución para detectar tuits procedentes de Barcelona.
[cols="3,1", id="experiment-spain-barcelona"]
|===
|Acierto
|98.25%

|Exhaustividad
|65.73%

|Acierto en predicciones locales
|97.09%

|Acierto en predicciones globales
|98.29%
|===

===== Barcelona y el impacto del catalán

Uno de los aspectos más curiosos de los resultados y puntuaciones generadas por el algoritmo Log Likelihood-Ratio fue comprobar como entre los términos más discriminativos para la provincia de Barcelona se encontraban, en su mayoría, vocablos en catalán.

Esto certifica de manera empírica las intuiciones acerca de la validez del algoritmo para este tipo de problema, siendo capaz de detectar que los términos en catalán, con una frecuencia muy baja a nivel global y relativamente alta en Barcelona, son los más significativos para identificar al territorio.

.Bigramas más discriminativos para encontrar tuits procedentes de la provincia de Barcelona
----
94.52274667047315   per tres
100.19650868429694  per dos
100.19650868429694  salón barcelona
100.19650868429694  ara per
100.19650868429694  acuerdo leo
100.19650868429694  gracias horas
100.19650868429694  debat els
101.79780787750204  buenos barcelona
111.11339666895931  catalunya és
111.11339666895931  avui amb
----

==== Resultados a nivel de área metropolitana

Para la granularidad a nivel de área metropolitana, se utilizaron las tres metrópolis más importantes del Reino Unido: *Manchester*, *Birminghan* y *Londres*. El proceso para generar los conjuntos de datos utilizados para el análisis se basa en los mecanismos utilizados a nivel de provincia.

Las tablas <<experiment-uk-london>>, <<experiment-uk-manchester>> y <<experiment-uk-birminghan>> muestran los resultados para esta granularidad.

.Resultados de la ejecución para detectar tuits procedentes de Londres.
[cols="3,1", id="experiment-uk-london"]
|===
|Acierto
|91.69%

|Exhaustividad
|70.98%

|Acierto en predicciones locales
|86.43%

|Acierto en predicciones globales
|92.77%
|===

.Resultados de la ejecución para detectar tuits procedentes de Manchester.
[cols="3,1", id="experiment-uk-manchester"]
|===
|Acierto
|96.68%

|Exhaustividad
|51.10%

|Acierto en predicciones locales
|88.53%

|Acierto en predicciones globales
|96.97%
|===

.Resultados de la ejecución para detectar tuits procedentes de Birminghan.
[cols="3,1", id="experiment-uk-birminghan"]
|===
|Acierto
|97.22%

|Exhaustividad
|47.05%

|Acierto en predicciones locales
|97.95%

|Acierto en predicciones globales
|97.20%
|===

==== Resultados a nivel de barrio

Por último, se realizó un experimento a nivel de barrio, siendo la granularidad más baja analizada en el proyecto. Para ello, se utilizaron los 3 barrios más importantes de Londres como área local (*Wandsworth*, *Lambeth* y *Southwark*), así como la ciudad de Londres como área global. Los resultados de este experimento se pueden consultar en las tablas <<experiment-london-wandsworth>>, <<experiment-london-lambeth>> y <<experiment-london-southwark>>.

.Resultados de la ejecución para detectar tuits procedentes de Wandsworth.
[cols="3,1", id="experiment-london-wandsworth"]
|===
|Acierto
|99.54%

|Exhaustividad
|18.18%

|Acierto en predicciones locales
|100.0%

|Acierto en predicciones globales
|99.54%
|===

.Resultados de la ejecución para detectar tuits procedentes de Lambeth.
[cols="3,1", id="experiment-london-lambeth"]
|===
|Acierto
|99.20%

|Exhaustividad
|24.13%

|Acierto en predicciones locales
|87.5%

|Acierto en predicciones globales
|99.23%
|===

.Resultados de la ejecución para detectar tuits procedentes de Southwark.
[cols="3,1", id="experiment-london-southwark"]
|===
|Acierto
|98.98%

|Exhaustividad
|25.0%

|Acierto en predicciones locales
|90.0%

|Acierto en predicciones globales
|99.01%
|===
