=== Pseudocódigo para ilustrar el proceso completo de análisis de tuits

Los siguientes fragmentos de _pseudocódigo_ muestran los diferentes algoritmos que se han utilizado para obtener la frecuencia de términos en los diferentes datasets, así como el proceso para realizar el cálculo de su Log Likelihood-Ratio asociado y la manera de computar la puntuación total de cada tuit en función de la puntuación de cada uno de los términos que contiene.

<<<

.Algoritmo para extraer la frecuencia de cada término
----
for each tweet in tweets do
  terms = apply_extractor_filter(tweet)
  check_memory_status()
  for each term in terms do
    if frequencies[term].is_defined then
      frequencies[term] += 1
    else
      frequencies[term] = minimum_frequency
    end
  end
end

def check_memory_status
  if frequencies.size >= MAXIMUM_EXTRACTED_TERMS then
    reduce_map_load()
  end
end

def reduce_map_load
  items_to_remove   = frequencies.size * FACTOR_TO_REMOVE
  ordered_map       = frequencies.order_by_frequency
  minimum_frequency = ordered_map.get(items_to_remove - 1)

  ordered_map.slice from items_to_remove - 1 to ordered_map.size
end

----

<<<

.Algoritmo para calcular la puntuación LLR de cada término
----
for each term in locals do
  freq = locals[term]
  if freq > min_frequency then
    global_freq = get_global_freq(term)
    if global_freq > 0 then
      k11 = freq
      k12 = global_freq
      k21 = total_local_frequencies
      k22 = total_global_frequencies
      llr = Dunning.normalized_llr(k11, k12, k21, k22)
      results[term] => llr
    end
  end
end

def get_global_freq(term)
  globals[term].is_defined ? globals[term] : avg_global_freq(term)
end

def avg_global_freq(term)
  same_freq_in_local = locals.select(
    t => globals[t].is_defined && locals[t] == locals[term]
  )
  acc = same_freq_in_local.map(t => globals[t]).reduce(
    (previous, current) => previous + current
  )
  return acc / same_freq_in_local.size
end
----

.Algoritmo para calcular la puntuación LLR de cada tuit
----
for each tweet in tweets do
  terms = extract_terms(tweet)
  score = terms.reduce(
    (previous, current) => previous + get_llr_score(current)
  )
  results[tweet] = score
end
----
