== Herramientas utilizadas durante el desarrollo del Proyecto

Además de las tecnologías utilizadas para el desarrollo de los prototipos y experimentos presentados en capítulos anteriores, el presente proyecto ha hecho uso de una serie de herramientas que facilitaron el desarrollo del mismo desde las fases iniciales hasta el desarrollo de la documentación final.

=== Trello

*Trello* (https://trello.com/) es una aplicación web desarrollada por *Fog Creek* con el objetivo de ofrecer una herramienta eficaz para la gestión de tareas (y en cierta medida, proyectos) de manera sencilla y muy colaborativa que potencie los procesos de desarrollos ágiles.

Trello basa su funcionamiento en establecer una serie de tablones en donde los diferentes usuarios de una organización o equipo puedan ir colocando tareas (en forma de tarjeta) en un conjunto de columnas totalmente personalizables. Su funcionamiento se basa en metodologías ágiles como *Scrumfootnote:[https://www.scrum.org/resources/what-is-scrum/]*, donde el _Scrum Board_ se utiliza para recoger todas las tareas *Pendientes*, *En progreso* o *Terminadas* para el _sprint_ en curso.

En este caso se ha utilizado como herramienta para organizar y controlar el progreso de las tareas en las estaciones de experimentación y prototipado.

=== OmniGraffle y Balsamiq Mockup

Ambas herramientas se han utilizado a la hora de realizar la documentación del proyecto con la misión de realizar gráficos que permitan reflejar, en el caso de *OmniGraffle* los diagramas UML necesarios para explicar el análisis y diseño de la aplicación web propuesta y, en el caso de *Balsamiq Mockup* ejemplos de interfaces de usuario que se podrían implementar para facilitar la interacción del usuario con la aplicación web.

=== Desarrollo de la documentación utilizando AsciiDoc

*AsciiDoc* (http://www.methods.co.nz/asciidoc/) ha sido el lenguaje de marcado seleccionado para realizar la documentación del proyecto, apoyado sobre el procesador *Asciidoctor* (http://asciidoctor.org/).

La herramienta seleccionada para realizar la documentación debía de cumplir con las siguientes seis condiciones:

. Trabajar en un formato de texto simple, preferiblemente texto plano, que lo hiciera independiente de la plataforma sobre la que realizar la documentación.

. Trabajar con un lenguaje de marcado sencillo (similar a *Markdownfootnote:[http://daringfireball.net/projects/markdown/]*) que simplificara el proceso de escritura ante alternativas como LaTeX.

. Capacidad de dividir la documentación en varios ficheros que se pudiesen estructurar en base a directorios internos del proyecto de documentación.

. Permitir el uso de un repositorio de código (como Bitbucket o Github) como sistema de control de versiones (utilizando para ello Mercurial o Git).

. Ser Open Source, libre y gratuito.

. Ser capaz de generar un documento en formato PDF con un resultado similar al de sistemas como LaTeX.

AsciiDoc, mediante la utilización de Asciidoctor y el procesador *asciidoctor-fopub* (https://github.com/asciidoctor/asciidoctor-fopub) permitió generar de manera sencilla un pequeño proyecto basado en tecnologías Ruby que cumpliera con todos los requisitos anteriores.

A través de una serie de ficheros en texto plano escritos con AsciiDoc y respaldados por un repositorio en Bitbucket, se realizaba un compilado de los ficheros fuente utilizando Asciidoctor y *Guardfootnote:[http://guardgem.org/ - gema de Ruby para detectar cambios en ficheros de un directorio]* para producir un documento *DocBookfootnote:[http://www.docbook.org/whatis]* válido en XML que se pudiera transformar automáticamente en el PDF resultado utilizando asciidoctor-fopub.
